spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console.enabled: true
  zipkin:
    base-url: http://localhost:9411/
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
app:
  name: course service for the school managament project..
  api:
    title: course service
    version: 1.0.0
    description: Rest api for the courses program
    base-package: com.sam.microservices
    contact-name: achrafcharif
    contact-email: m.charif.achraf@gmail.com
    swagger:
      enable: true