spring:
  zipkin:
    base-url: http://localhost:9411/
  cloud:
    gateway:
      routes: 
        - id: staffs-service
          uri: lb://staffs-service
          predicates: 
            - Path=/students/**
        - id: courses-service
          uri: lb://courses-service
          predicates: 
            - Path=/courses/**