spring:
  cloud:
    gateway:
      routes: 
        - id: currency-exchange
          uri: lb://currency-exchange
          predicates: 
            - Path=/currency-exchange/**
        - id: currency-conversion
          uri: lb://currency-conversion
          predicates: 
            - Path=/currency-conversion/**, /currency-conversion-feign/**