spring:
  cloud:
    gateway:
      routes: 
        - id: staffs-service
          uri: lb://staffs-service
          predicates: 
            - Path=/student/**
        - id: currency-conversion
          uri: lb://currency-conversion
          predicates: 
            - Path=/currency-conversion/**, /currency-conversion-feign/**